apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: unprivileged-
commonLabels:
  run-as: non-root
resources:
- ../privileged
images:
- name: nginx
  newName: docker.io/nginxinc/nginx-unprivileged
